module BoggleApp {
    struct Leaderboard {
        string username;
        long points;
    };
    typedef sequence<Leaderboard> userRanking;

    interface BoggleClient {
        boolean validateAccount(in string username, in string password);

        long long attemptJoin();

        long joinGameRoom(out long long duration);

        long getCurrLobbyTimerValue();

        long startRound(in string username, in long gameID, out long roundNumber, out string vowels, out string consonants);

        long long getGameDurationVal(in long gameID, in long roundID);

        string getRoundWinner(in string username, in long gameID, in long roundID, in string wordsEntered);

        string getOverallWinner(in long gameId);

        long getPoints(in string username);

        string getWinnerIfAny(in long gameID);

        string getWordList(in long gameID, in long roundID);

        userRanking getLeaderboard();

        long getUserPoints(in string username);

        boolean editInfo(in string username, in string toEdit, in string newInfo);
        long getMatches(in string username);
        long getWins(in string username);
        boolean editPassword(in string username, in string oldPass, in string newPass);
    };
};
