package server.model.WordFactoryApp;


/**
* WordFactoryApp/WordFactoryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordFactory.idl
* Sunday, April 14, 2024 3:19:00 PM PST
*/

public abstract class WordFactoryPOA extends org.omg.PortableServer.Servant
 implements WordFactoryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("getUsername", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WordFactoryApp/WordFactory/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // WordFactoryApp/WordFactory/getUsername
       {
         int playerID = in.read_long ();
         String $result = null;
         $result = this.getUsername (playerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordFactoryApp/WordFactory:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public WordFactory _this() 
  {
    return WordFactoryHelper.narrow(
    super._this_object());
  }

  public WordFactory _this(org.omg.CORBA.ORB orb) 
  {
    return WordFactoryHelper.narrow(
    super._this_object(orb));
  }


} // class WordFactoryPOA
