package server.model.WordFactoryApp;


/**
* WordFactoryApp/WordFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordFactory.idl
* Sunday, April 14, 2024 3:19:00 PM PST
*/

public interface WordFactoryOperations 
{
  String sayHello ();
  String getUsername (int playerID);
} // interface WordFactoryOperations
