package server.model.BoggleApp;


/**
* BoggleApp/BoggleClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoggleClient.idl
* Saturday, April 27, 2024 3:33:41 PM CST
*/

public interface BoggleClient extends BoggleClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoggleClient
