package server.model.BoggleApp;


/**
* server.model.client.model.BoggleApp/BoggleClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from shared/BoggleClient.idl
* Friday, May 3, 2024 7:37:10 AM PST
*/

public interface BoggleClient extends BoggleClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoggleClient
