package server.model.BoggleApp;

/**
* BoggleApp/LeaderboardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoggleClient.idl
* Saturday, April 27, 2024 3:33:41 PM CST
*/

public final class LeaderboardHolder implements org.omg.CORBA.portable.Streamable
{
  public Leaderboard value = null;

  public LeaderboardHolder ()
  {
  }

  public LeaderboardHolder (Leaderboard initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LeaderboardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LeaderboardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LeaderboardHelper.type ();
  }

}
