package server.model.BoggleApp;


/**
* server.model.client.model.BoggleApp/LobbyUser.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from shared/BoggleClient.idl
* Thursday, May 2, 2024 3:01:08 PM PST
*/

public final class LobbyUser implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public String pfpAddress = null;

  public LobbyUser ()
  {
  } // ctor

  public LobbyUser (String _username, String _pfpAddress)
  {
    username = _username;
    pfpAddress = _pfpAddress;
  } // ctor

} // class LobbyUser
