package server.model.BoggleApp;


/**
* server.model.client.model.BoggleApp/updateFailed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from shared/BoggleClient.idl
* Thursday, May 2, 2024 6:15:57 PM PST
*/

public final class updateFailed extends org.omg.CORBA.UserException
{
  public String reason = null;

  public updateFailed ()
  {
    super(updateFailedHelper.id());
  } // ctor

  public updateFailed (String _reason)
  {
    super(updateFailedHelper.id());
    reason = _reason;
  } // ctor


  public updateFailed (String $reason, String _reason)
  {
    super(updateFailedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class updateFailed
