package server.model.BoggleApp;


/**
* server.model.client.model.BoggleApp/wordListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from shared/BoggleClient.idl
* Friday, May 3, 2024 7:37:10 AM PST
*/

public final class wordListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public wordListHolder ()
  {
  }

  public wordListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordListHelper.type ();
  }

}
