package server.model.BoggleApp;


/**
* BoggleApp/wrongCredentials.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoggleClient.idl
* Thursday, May 2, 2024 1:23:41 PM PST
*/

public final class wrongCredentials extends org.omg.CORBA.UserException
{
  public String reason = null;

  public wrongCredentials ()
  {
    super(wrongCredentialsHelper.id());
  } // ctor

  public wrongCredentials (String _reason)
  {
    super(wrongCredentialsHelper.id());
    reason = _reason;
  } // ctor


  public wrongCredentials (String $reason, String _reason)
  {
    super(wrongCredentialsHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class wrongCredentials
