package Server_Java.model.BoggleApp;

/**
* BoggleApp/accountLoggedInHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoggleClient.idl
* Sunday, May 12, 2024 2:09:46 PM PST
*/

public final class accountLoggedInHolder implements org.omg.CORBA.portable.Streamable
{
  public accountLoggedIn value = null;

  public accountLoggedInHolder ()
  {
  }

  public accountLoggedInHolder (accountLoggedIn initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = accountLoggedInHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    accountLoggedInHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return accountLoggedInHelper.type ();
  }

}
