package client.model.BoggleApp;


/**
* BoggleApp/BoggleClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoggleClient.idl
* Thursday, May 2, 2024 1:27:51 PM PST
*/

public interface BoggleClientOperations 
{
  void validateAccount (String username, String password) throws wrongCredentials, accountDoesNotExist;
  void attemptJoin (String username);
  LobbyUser[] getLobbyMembers ();
  long getCurrLobbyTimerValue ();
  int joinGameRoom (org.omg.CORBA.LongHolder duration);
  void startRound (int gameID, org.omg.CORBA.IntHolder roundNumber, org.omg.CORBA.StringHolder letterList);
  long getGameDurationVal (int gameID);
  void sendUserWordList (int gameID, String username, String[] wordList);
  void exitGameRoom (String username);
  String getOverallWinner (int gameID);
  String getRoundWinner (int gameID);
  userInfo[] getLeaderboard ();
  void editInfo (String username, String toEdit, String newInfo) throws updateFailed;
  int getUserPoints (String username);
  int getMatches (String username);
  int getWins (String username);
  boolean editPassword (String username, String oldPass, String newPass);
  int getGamePoints (String username);
  userInfo[] getCurrGameLeaderboard (int gameID);
} // interface BoggleClientOperations
