package client.model.BoggleApp;


/**
* BoggleApp/BoggleClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoggleClient.idl
* Wednesday, April 24, 2024 10:36:58 AM PST
*/

public interface BoggleClient extends BoggleClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoggleClient
