package client.model.BoggleApp;


/**
* BoggleApp/BoggleClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoggleClient.idl
* Saturday, April 20, 2024 8:22:19 PM PST
*/

public interface BoggleClient extends BoggleClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoggleClient
