package Client_Java.model.BoggleApp;

/**
* BoggleApp/accountDoesNotExistHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoggleClient.idl
* Sunday, May 12, 2024 2:16:16 PM PST
*/

public final class accountDoesNotExistHolder implements org.omg.CORBA.portable.Streamable
{
  public accountDoesNotExist value = null;

  public accountDoesNotExistHolder ()
  {
  }

  public accountDoesNotExistHolder (accountDoesNotExist initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = accountDoesNotExistHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    accountDoesNotExistHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return accountDoesNotExistHelper.type ();
  }

}
