package Client_Java.model.BoggleApp;


/**
* BoggleApp/BoggleClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoggleClient.idl
* Sunday, May 12, 2024 2:16:16 PM PST
*/

public interface BoggleClient extends BoggleClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoggleClient
