package client_java.model.WordFactoryApp;

/**
* WordFactoryApp/WordFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordFactory.idl
* Sunday, April 14, 2024 3:22:45 PM PST
*/

public final class WordFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public WordFactory value = null;

  public WordFactoryHolder ()
  {
  }

  public WordFactoryHolder (WordFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordFactoryHelper.type ();
  }

}
