package client_java.model.WordFactoryApp;


/**
* WordFactoryApp/WordFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordFactory.idl
* Sunday, April 14, 2024 3:22:45 PM PST
*/

public interface WordFactory extends WordFactoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordFactory
